### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by kassing3** [kassing3/Module2-Challenge-Portfolio#2]
#HTML

##User Story
As a bootcamp student,
I want my portfolio to have a stylish webpage
so that the aesthetic of my portfolio captivates employers

##Accepance Criteria
GIVEN a portfolio website
WHEN Employers visit my portfolio site
THEN they see the following

 

- [ ] Branded Colors
- [ ]  Brande Fonts and backup fonts
- [ ] Fixe Navigation Bar
- [ ]  "My Projects" section contains images with the first project image larger than others
- [ ]  Proportionate sections, icons, images, and texts

**Comment by Andyy-18** [comment]
Hey @kassing3 
I can try my best. 
Shall you assign me?
